name: AutoDeploy-Prod
on:
  release:
    types:
      - published

env:
  INSTALL_GLOBAL: true

jobs:
  publish-html5-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Sparse checkout FMOD SDK (html5 only)
        run: |
          git clone --no-checkout --filter=blob:none \
            https://x-access-token:${{ secrets.FMOD_SDK_TOKEN }}@github.com/Tanz0rz/fmod-sdk-cache.git \
            fmod-sdk-cache
          cd fmod-sdk-cache
          git sparse-checkout set sdk/2.03.12/html5
          git checkout

      - name: Make html5 build
        uses: bitDecayGames/lime-build-action@v0.0.39
        with:
          buildArgs: -final -D API_KEY=${{ secrets.ANALYTICS_TOKEN }}
          initScriptFile: ./bin/init_deps.sh
        env:
          FMOD_SDK_WEB: ${{ github.workspace }}/fmod-sdk-cache/sdk/2.03.12/html5

      - name: Upload html5 zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: html5-build
          path: export/html5.zip
          retention-days: 7

      - name: Publish html5 build to itch.io
        uses: bitDecayGames/butler-deploy-action@v0.0.2
        with:
          dir: export/html5.zip
          itchUserName: bitdecaygames
          itchGameName: FrandsJam
          itchChannel: web-release
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
